02:27:18 AM:DEBUG [logger_base.py:15] Mensaje a nivel debug
02:27:18 AM:INFO [logger_base.py:16] Mensaje a nivel info
02:27:18 AM:WARNING [logger_base.py:17] Mensaje a nivel warning
02:27:18 AM:ERROR [logger_base.py:18] Mensaje a nivel error
02:27:18 AM:CRITICAL [logger_base.py:19] á¸¾ensaje a nivel critical
01:01:36 AM:DEBUG [Persona.py:52] 
            Id Persona:1,
            Nombre:Juan,
            Apellido: Perez,
            Email: jperez@mail.com
            
01:03:54 AM:DEBUG [Persona.py:52] 
            Id Persona:1,
            Nombre:Juan,
            Apellido: Perez,
            Email: jperez@mail.com
            
01:06:34 AM:DEBUG [Persona.py:55] 
            Id Persona:1,
            Nombre:Juan,
            Apellido: Perez,
            Email: jperez@mail.com
            
01:06:34 AM:DEBUG [Persona.py:57] 
            Id Persona:Jose,
            Nombre:Lepez,
            Apellido: ljose@mail.com,
            Email: None
            
01:07:08 AM:DEBUG [Persona.py:55] 
            Id Persona:1,
            Nombre:Juan,
            Apellido: Perez,
            Email: jperez@mail.com
            
01:07:08 AM:DEBUG [Persona.py:57] 
            Id Persona:None,
            Nombre:Jose,
            Apellido: Lepez,
            Email: ljose@mail.com
            
01:08:59 AM:DEBUG [Persona.py:55] 
            Id Persona:1,
            Nombre:Juan,
            Apellido: Perez,
            Email: jperez@mail.com
            
01:08:59 AM:DEBUG [Persona.py:57] 
            Id Persona:None,
            Nombre:Jose,
            Apellido: Lepez,
            Email: ljose@mail.com
            
01:08:59 AM:DEBUG [Persona.py:59] 
            Id Persona:1,
            Nombre:None,
            Apellido: None,
            Email: None
            
04:13:09 PM:DEBUG [conexion.py:22] Conexion Exitosa: <connection object at 0x7f26e813a0c0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
04:24:16 PM:DEBUG [conexion.py:22] Conexion Exitosa: <connection object at 0x7fe150baa0c0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
04:24:16 PM:ERROR [conexion.py:37] Ocurrio un error:'NoneType' object has no attribute 'cursor'
04:24:38 PM:DEBUG [conexion.py:22] Conexion Exitosa: <connection object at 0x7fcf389aa0c0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
04:24:38 PM:DEBUG [conexion.py:34] Se abrio correctamente el cursor: <cursor object at 0x7fcf389835b0; closed: 0>
